name: 📝 Add New Activity
description: Request to add a new extracurricular activity to the system
title: "[Activity] Add new activity: "
labels: ["enhancement", "activity"]
assignees:
  - copilot
body:
  - type: markdown
    attributes:
      value: |
        ## Add New Activity
        Fill out this form to request a new extracurricular activity be added to the system.
        
  - type: input
    id: activity-name
    attributes:
      label: Activity Name
      description: What is the name of the new activity?
      placeholder: e.g., Coding Club, Dance Team, Photography Club
    validations:
      required: true
      
  - type: textarea
    id: activity-description
    attributes:
      label: Description
      description: Describe what this activity is about
      placeholder: Provide a clear description that students will see when browsing activities
    validations:
      required: true
      
  - type: input
    id: activity-category
    attributes:
      label: Category
      description: What category does this activity fall under?
      placeholder: Choose one - sports, arts, academic, community, or technology
    validations:
      required: true
      
  - type: input
    id: activity-days
    attributes:
      label: Meeting Days
      description: Which day(s) of the week does this activity meet?
      placeholder: e.g., Monday and Wednesday, or Tuesday, Thursday, Friday
    validations:
      required: true
      
  - type: input
    id: activity-time
    attributes:
      label: Meeting Time
      description: What time does the activity meet?
      placeholder: e.g., 3:30 PM - 5:00 PM or 7:00 AM - 8:00 AM
    validations:
      required: true
      
  - type: input
    id: max-participants
    attributes:
      label: Maximum Participants
      description: How many students can participate?
      placeholder: e.g., 15, 20, 30
    validations:
      required: true
      
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details needed for this activity?
      placeholder: Special requirements, equipment needed, teacher sponsor, etc.
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ---
        ### Acceptance Criteria
        - New activity appears in the activities list
        - Students can view the activity details
        - Students can register for the activity (if logged in)
        - Activity filters (category, day, time) work correctly
        - Activity respects the maximum participant limit
        
        ### Technical Hints
        - Add the activity to the database initialization in `src/backend/database.py`
        - Ensure the `schedule_details` object includes `days` array, `start_time`, and `end_time`
        - Verify the category matches one of the existing filter categories
        - Test the activity appears correctly in the UI filters
