name: 🐛 Bug Report
description: Report something that isn't working correctly
title: "[Bug] "
labels: ["bug"]
assignees:
  - copilot
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Fill out this form to report something that's not working as expected.
        
  - type: textarea
    id: bug-description
    attributes:
      label: What's not working?
      description: Describe the problem in simple terms
      placeholder: e.g., "Students can't register for activities" or "The filter buttons don't work"
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How to see the problem
      description: What steps should someone take to see this bug?
      placeholder: |
        For example:
        1. Go to the activities page
        2. Click on an activity
        3. Try to register
        4. Nothing happens
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: What should happen instead?
      description: What did you expect to happen?
      placeholder: e.g., "The student should be added to the activity and see a confirmation message"
    validations:
      required: true
      
  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      description: Does this always happen or only sometimes?
      options:
        - Always - Every single time
        - Usually - Most of the time
        - Sometimes - Only occasionally
        - Once - Only happened once
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: How serious is this?
      description: How much does this impact using the system?
      options:
        - Critical - System is unusable
        - High - Major feature doesn't work
        - Medium - Feature works but has issues
        - Low - Minor inconvenience
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Any other details that might help?
      placeholder: Screenshots, error messages, which browser you're using, etc.
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ---
        ### Acceptance Criteria
        - The bug is identified and fixed
        - The expected behavior works correctly
        - No new bugs are introduced
        - Similar issues are also checked and fixed if found
        
        ### Technical Hints
        - Check browser console for JavaScript errors
        - Review API endpoints in `src/backend/routers/`
        - Check database operations in `src/backend/database.py`
        - Test the fix thoroughly before submitting
        - Ensure the fix doesn't break other features
