blank_issues_enabled: true
contact_links:
  - name: 💬 Questions and Support
    url: https://github.com/darkmusic/skills-expand-your-team-with-copilot/discussions
    about: Ask questions or get help from the community
